# app çš„å”¯ä¸€ id,ä¸Šæž¶åˆ°å•†åº—éœ€è¦ä¿è¯ä¸è¦å†²çª,å°½é‡ä½¿ç”¨å¼€å‘è€…è‡ªå·±çš„åŸŸåä½œä¸ºåŽç¼€.
package: cloud.lazycat.app.liu.appsmith
# app çš„ç‰ˆæœ¬
version: 1.87.0

name: Appsmith
keywords: appsmith,low-code,app-builder,no-code,workflow,automation
description: Appsmith is a low-code platform to build, deploy, and manage internal tools.

# è½¯ä»¶åç§°,ä¼šæ˜¾ç¤ºåœ¨å¯åŠ¨å™¨ä¹‹ç±»çš„åœ°æ–¹
locales:
  zh:
    name: Appsmith
    description: |
      ## Appsmith - å¼€æºä½Žä»£ç å¹³å°

      **å®˜æ–¹ç½‘ç«™:** https://www.appsmith.com/
      **ä»“åº“åœ°å€:** https://github.com/lazycatapps/appsmith.git

      Appsmith æ˜¯ä¸€ä¸ªå¼€æºä½Žä»£ç å¹³å°,ç”¨äºŽå¿«é€Ÿæž„å»ºã€éƒ¨ç½²å’Œç®¡ç†å†…éƒ¨å·¥å…·ã€‚é€šè¿‡æ‹–æ”¾å¼ç•Œé¢å’Œå¼ºå¤§çš„é›†æˆèƒ½åŠ›,å¼€å‘è€…å¯ä»¥å¿«é€Ÿåˆ›å»ºå®šåˆ¶åŒ–çš„åº”ç”¨ç¨‹åºã€‚

      ## ä¸»è¦åŠŸèƒ½

      - ðŸŽ¨ å¯è§†åŒ–æ‹–æ”¾ç•Œé¢è®¾è®¡å™¨
      - ðŸ”Œ æ”¯æŒå¤šç§æ•°æ®æºé›†æˆ (PostgreSQL, MongoDB, REST API ç­‰)
      - ðŸ“Š ä¸°å¯Œçš„ UI ç»„ä»¶åº“
      - ðŸš€ ä¸€é”®éƒ¨ç½²å’Œå‘å¸ƒ
      - ðŸ‘¥ åä½œå’Œç‰ˆæœ¬æŽ§åˆ¶
      - ðŸ”’ ä¼ä¸šçº§å®‰å…¨å’Œæƒé™ç®¡ç†

  en:
    name: Appsmith
    description: |
      ## Appsmith - Open Source Low-Code Platform

      **Official Website:** https://www.appsmith.com/
      **Repository:** https://github.com/lazycatapps/appsmith.git

      Appsmith is an open-source low-code platform for building, deploying, and managing internal tools. With a drag-and-drop interface and powerful integration capabilities, developers can quickly create custom applications.

      ## Key Features

      - ðŸŽ¨ Visual drag-and-drop interface designer
      - ðŸ”Œ Multiple data source integrations (PostgreSQL, MongoDB, REST API, etc.)
      - ðŸ“Š Rich UI component library
      - ðŸš€ One-click deployment and publishing
      - ðŸ‘¥ Collaboration and version control
      - ðŸ”’ Enterprise-grade security and permissions

# è½¯ä»¶æœ¬èº«çš„ license
license: https://github.com/appsmithorg/appsmith?tab=Apache-2.0-1-ov-file

# è½¯ä»¶çš„ä¸»é¡µ,ä¼šåœ¨å•†åº—ç­‰åœ°æ–¹ä½“çŽ°
homepage: https://github.com/appsmithorg/appsmith

# lpk çš„ä½œè€…,ä¼šåœ¨å•†åº—ç­‰åœ°æ–¹ä½“çŽ°
author: liu

# application ä½œä¸ºä¸€ä¸ªç‰¹æ®Šçš„ container è¿è¡Œï¼Œå¯¹åº”çš„ service åç§°ä¸ºå›ºå®šçš„`app`ï¼Œ å…¶ä»– service å¯ä»¥é€šè¿‡æ­¤åç§°ä¸Ž app è¿›è¡Œé€šè®¯
application:
  #æ˜¯å¦å­˜åœ¨åŽå°ä»»åŠ¡ï¼Œ è‹¥å­˜åœ¨åˆ™ç³»ç»Ÿä¸ä¼šå¯¹æ­¤ app è¿›è¡Œä¸»åŠ¨ä¼‘çœ ç­‰æ“ä½œ
  background_task: true

  # æœŸæœ›çš„ app åŸŸåï¼Œå¦‚æžœç³»ç»Ÿä¸­å·²ç»æœ‰å¯¹åº”åŸŸååˆ™ä¼šæç¤ºç”¨æˆ·é€‰æ‹©å…¶ä»–åŸŸåã€‚ æœ€ç»ˆ app åˆ†é…åˆ°çš„åŸŸåä»¥/lzcapp/run/app.subdomain ä¸ºå‡†
  subdomain: appsmith

  routes:
    - /=http://appsmith:80/

  # é¡µé¢æœ¬èº«æ˜¯æœ‰é‰´æƒçš„ï¼Œæ‰€ä»¥å¯ä»¥ä¸éœ€è¦ lazycat çš„é‰´æƒã€‚
  public_path:
    - /                         # æ— éœ€ç™»å½•å³å¯è®¿é—®

  # å¥åº·æ£€æµ‹é…ç½®
  health_check:
    test_url: http://appsmith:80
    start_period: 120s

  depends_on:
    - appsmith

  # æ˜¯å¦å¯ç”¨å¤šå®žä¾‹
  multi_instance: false

services:
  appsmith:
    # lzc-cli appstore copy-image index.docker.io/appsmith/appsmith-ee:v1.87
    image: registry.lazycat.cloud/liu/appsmith/appsmith-ee:66c9907b4c55b5bd
    environment:
      - APPSMITH_ENCRYPTION_PASSWORD=changeme_please_use_secure_random_value
      - APPSMITH_ENCRYPTION_SALT=changeme_please_use_secure_random_value
      - APPSMITH_SUPERVISOR_PASSWORD=changeme_supervisor_password
      - APPSMITH_DISABLE_TELEMETRY=true
      - APPSMITH_SEGMENT_CE_KEY=
    binds:
      - /lzcapp/var/stacks:/appsmith-stacks
    setup_script: |
      #!/bin/sh
      # æ›¿æ¢ç³»ç»Ÿçš„ update-ca-certificates å‘½ä»¤ä¸ºç©ºæ“ä½œ
      # å› ä¸ºæ‡’çŒ«å¾®æœå·²æŒ‚è½½åªè¯»çš„ /etc/ssl/certs/ca-certificates.crt
      mv /usr/sbin/update-ca-certificates /usr/sbin/update-ca-certificates.orig
      cat > /usr/sbin/update-ca-certificates << 'EOF'
      #!/bin/sh
      echo "Skip update-ca-certificates (CA certificates mounted read-only by lzc-os)"
      exit 0
      EOF
      chmod +x /usr/sbin/update-ca-certificates
